### ISSUE TITLE
[BUG] Select a Directory doesn't load when really large

### ISSUE THREAD

**Issue by Daniverzum** [stumpapp/stump#589]
## Description of the Bug

Select a Directory when creating a new Library doesn't load subfolders if there are special characters in the folder name

## Expected Behavior

When selecting a folder with special characters in its name(for example "Letöltések" or "Könyvek"), it should display subfolders for further specifying the selection of the library folder

## To Reproduce

1. Go to Create Library
2. Click on Path
3. Try to select a folder with special characters in its name
4. See that it doesn't load subfolders

**Environment:**

- OS: Windows

**Build Details:**

- Version: 0.0.10
- Docker: no

**Additional context**

Okay I realized "Képek" for example works, so I assume it accepts like french? Hungarian has áéöóőüúűí special characters but I assume people could have even fancier folder names.

Okay, just checked and it doesn't work with Japanese either, so...

**Comment by aaronleopold** [comment]
I wasn't able to reproduce on macOS, unfortunately. I'll try to boot up a Windows machine sometime this week to figure out what might be happening.

<details>

<summary>Screenshots</summary>

<img width="1624" alt="Image" src="https://github.com/user-attachments/assets/7dd966ed-9995-4ab1-8562-9e8184fe9bd0" />

<img width="1624" alt="Image" src="https://github.com/user-attachments/assets/a0f4af7d-961f-4a0b-9c2c-bf2223d42991" />

</details>

**Comment by Daniverzum** [comment]
Hmm, I checked again, sorry Japanese seems to work, I think I might have opened a folder that didn't have subfolders while checking quickly.

Now that I look at it more other folders seem to work, it's only the "Letöltések" folder, which is my downloads folder, and has 800+ files and is 120 GB, but well that's where my books are as well

**Comment by Daniverzum** [comment]
yeah I found another folder that doesn't work and it's just a folder with 933 images and 5 subfolders in it that don't show up.

i might have jumped to conclusions with the special characters, it seems that the number of files in the folder is the problem

**Comment by aaronleopold** [comment]
> [The "Letöltések" folder] has 800+ files and is 120 GB... it seems that the number of files in the folder is the problem

Yeah that sounds about right! I'll try and get a repro setup sometime soon to figure out exactly what might be happening

**Comment by ItsNoted** [comment]
I noticed with Chrome based browsers, loading libraries with hundreds of books on a page lags a lot. I tried in Firefox and its much smoother but Edge also lags a lot. I think it has something to do with the thumbnails loading? I do not have thumbnail generation enabled. Would that help?

**Comment by aaronleopold** [comment]
@ItsNoted Are you referring to the "select a directory" modal for your issue? If so, it isn't related to thumbnails because the directory picker doesn't use any. It's more likely that it just needs some virtualization and performance tweaks for large sets of data. It's one of the oldest bits of the codebase, so just needs some love.

If you weren't referring to the directory picker, but speaking more generally while using Stump, not having thumbnails generated will definitely lag on the first load for a page with lots of images. When you don't generate thumbnails, it pulls the full resolution image from your media. While the browser should be caching them, that initial load will still be sub-optimal.

**Comment by aaronleopold** [comment]
@Daniverzum I have a tentative fix, but don't know if I have any directories large enough to trigger the issue. If I build you a Windows executable over the weekend, would you be able to test it?

**Comment by Daniverzum** [comment]
sure, I can do that

**Comment by DieselTech** [comment]
I can test this. Let me know if it goes lives in docker.

**Comment by aaronleopold** [comment]
@DieselTech I pushed a `nightly-fix-list-dir` image to docker hub. I'll try to get a Windows build at some point today, as well

**Comment by aaronleopold** [comment]
@Daniverzum A windows binary with the changes can be found here: https://github.com/stumpapp/stump/releases/tag/untagged-45f15cd0daca37025db7

**Comment by Daniverzum** [comment]
> https://github.com/stumpapp/stump/releases/tag/untagged-45f15cd0daca37025db7
uhh, "Page not found"

**Comment by aaronleopold** [comment]
> > https://github.com/stumpapp/stump/releases/tag/untagged-45f15cd0daca37025db7
> 
> uhh, "Page not found"

Interesting, I can access it fine. Maybe there are access rules for draft releases I am not aware of. Here is a download link: https://wormhole.app/eEEnYL#l1YsZxL5cW3ev53fo4wTpg

**Comment by Daniverzum** [comment]
hmm... the two folders I checked last time still don't work

but I tried a 3rd big folder I just remembered and that loads a single subfolder out of 19, but I think that might be because alphabetically that would be a the first item in the directory

then I checked with the v.0.0.10 release and that also loads the first folder there

**Comment by aaronleopold** [comment]
> hmm... the two folders I checked last time still don't work

Okay, so how many folders exactly are you expecting to see when you click into those folders? Or, do you not even see the folders at all?

> but I tried a 3rd big folder I just remembered and that loads a single subfolder out of 19, but I think that might be because alphabetically that would be a the first item in the directory

So with the new changes, are you saying it loads 1 out of 19 folders?

I think at this point, would you be able to clear the log file, set verbosity to 4, restart your server, reproduce the issue, and then send me the log file?

**Comment by Daniverzum** [comment]
while testing I also managed to create a critical error lol, i clicked on "System Volume Information", probably because it is a folder that is inaccessible even with administrator

![Image](https://github.com/user-attachments/assets/889373a7-a1ab-4947-9252-3dc0a606b269)

Zm@http://localhost:10801/assets/index-6db5b270.js:38:12804
b@http://localhost:10801/assets/index-6db5b270.js:38:17864
fn@http://localhost:10801/assets/index-6db5b270.js:40:1479
IU@http://localhost:10801/assets/index-6db5b270.js:40:45799
_U@http://localhost:10801/assets/index-6db5b270.js:40:39813
gee@http://localhost:10801/assets/index-6db5b270.js:40:39740
vy@http://localhost:10801/assets/index-6db5b270.js:40:39589
g1@http://localhost:10801/assets/index-6db5b270.js:40:35953
EU@http://localhost:10801/assets/index-6db5b270.js:40:34900
x@http://localhost:10801/assets/index-6db5b270.js:25:1554
M@http://localhost:10801/assets/index-6db5b270.js:25:1915

**Comment by Daniverzum** [comment]
> Okay, so how many folders exactly are you expecting to see when you click into those folders? Or, do you not even see the folders at all?

i expect to see 20, 19 and 5 subfolders in the three folders I check, but I see 0, 1, and 0

> So with the new changes, are you saying it loads 1 out of 19 folders?

I checked and that one folder loads with the normal v.0.0.10 release as well not just the new version, and it is probably because of all the items in the folder it is the first one alphabetically, so it gets loaded but then nothing else happens

and here are the logs:

[Stump.log](https://github.com/user-attachments/files/18812516/Stump.log)

**Comment by Daniverzum** [comment]
this is when it loads one folder: [Stump.log](https://github.com/user-attachments/files/18812526/Stump.log)

![Image](https://github.com/user-attachments/assets/0933714a-0ba8-495e-aa0d-7bfe0a3c9b62)

![Image](https://github.com/user-attachments/assets/0f991f5d-9cbf-463a-9068-2dc028133c54)

**Comment by aaronleopold** [comment]
Muhahaha okay, I might have figured it out. Thank you for the logs and screenshots!! I _think_ the problem is that the UI handled the filtering out of files, and by default all non-folders are filtered out. So, if a page had all files it would trick the client.

Rust came to the rescue, because the `target` folder has LOADS of artifact files and some folders, so I was finally able to repro your issue. I'll comment again when I have another binary for you to try

**Comment by aaronleopold** [comment]
Okay, I'm hopeful this fixes it. The download link: https://wormhole.app/vbbyr4#JOlsxDeJPRY_4X506glceg

You'll need to replace your client folder, as well (included in the zip)

Also attaching some screenshots of how I was testing it, in case you're curious. The first is before the change (nothing loaded), the second is after (a few folders loaded). The folder has over 14k files

<img width="1762" alt="Image" src="https://github.com/user-attachments/assets/419ee9b1-8db7-474d-ad4d-d82e58dd657d" />

<img width="1762" alt="Image" src="https://github.com/user-attachments/assets/e05106c9-24f0-40fe-8674-718eb3e9dc52" />

**Comment by Daniverzum** [comment]
Yep, it works fine now

**Comment by aaronleopold** [comment]
Woohoo 🎊 Thanks for bearing with me as I was working through the bug. I'll close this issue one I merge the fix to `nightly`
